version: '3.8'
services:
  request-management-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis-dev-server.postgres.database.azure.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TRIP_MIN_LEAD_TIME_MINUTES: 30
      TRIP_MAX_UPCOMING_TRIPS: 30
      TRIP_MAX_TRIPS_PER_DAY: 5
      TRIP_MAX_TRIPS_TODAY: 5
      ROUTE_SERVICE_URL: http://localhost:8002/route
      GENDER_SERVICE_URL_TEMPLATE: https://localhost:8080/api/profiles/gender/{userId}
      MATCHING_CONSUMER_POLL_DELAY_MS: 60000
      NATS_RECONNECT_WAIT_SECONDS: 10
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data: 